### PR TITLE
add php 5.6 and 7.0 to travis

### PR DESCRIPTION
**Pull request by omansour**

### CODE REVIEW

**Comment by mikaelrandy** [comment]
There is something missing on this PR ?
It is still WIP ?

**Comment by omansour** [comment]
@mikaelrandy les tests passent pas sur php7 :/

cc @fabdsp

**Comment by fabdsp** [comment]
@omansour je vais fouiller, mais c'est un core dump :sob:

**Comment by omansour** [comment]
problem solved :)

**Comment by fabdsp** [comment]
:+1:

**Comment by mikaelrandy** [comment]
:+1:

**Pull request merged**
