### PR TITLE
Use static:: instead of self:: to allow overload of this methods

### PR DESCRIPTION
**Pull request by ChoOo7**

### CODE REVIEW

**Comment by mikaelrandy** [comment]
Why not, but as the `map{Request,Response}` methods are pretty generic, can you give us a use case of overloading ?

**Comment by ChoOo7** [comment]
I have to change the symfony request behavior

My CDN (CDNetworks) add a custom HTTP header (X-INITIAL-URL) wich the true requested URL inside.
I parse this header and modify my symfonyRequest object in order to map know headers like X-Forwarded-Host & X-Forwaded-proto.

My code : 

`

```
protected static function mapRequest(ReactRequest $reactRequest, $content)
{
    $headers = $reactRequest->getHeaders();
    $headersModified = false;
    foreach($headers as $headName=>$headerValue) {
        $headName = strtoupper($headName);

        if (in_array($headName, ['X-INITIAL-URL', 'X_INITIAL_URL','HTTP-X-INITIAL-URL', 'HTTP_X_INITIAL_URL'])) {
            $url = $headerValue;
            $host = parse_url($url, PHP_URL_HOST);
            $proto = strpos($url, 'https://') === 0 ? "https" : "http";
            $port = $proto == "https" ? 443 : 80;

            $headers['X-Forwarded-Host'] = $host;
            $headers['X-Forwarded-Port'] = $port;
            $headers['X-Forwarded-Proto'] = $proto;

            $headersModified = true;
        }
    }

    $symfonyRequest = parent::mapRequest($reactRequest, $content);

    if($headersModified)
    {
        $symfonyRequest->headers->replace($headers);
    }
    $symfonyRequest->server->set('REMOTE_ADDR', '127.0.0.1');//To force Trusted proxy to true

    return $symfonyRequest;
}
```

`

Before, a similar code was done in app.php (I modify the $_SERVER object before the symfony request loading)

Thanks

**Comment by mikaelrandy** [comment]
ok, agreed

👍

**Comment by omansour** [comment]
@fabdsp can you merge and release ? txs :)

**Comment by fabdsp** [comment]
:+1:

**Comment by fabdsp** [comment]
v1.2.1

**Pull request merged**
